# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockenv < Formula
  desc "Simple, CLI-friendly secret storage"
  homepage "https://github.com/illarion/lockenv"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/illarion/lockenv/releases/download/v0.1.1/lockenv_0.1.1_darwin_amd64.tar.gz"
      sha256 "ed207d01b75f5385ad086f94f91121177fef769b49ddbb628c1298c4f8e7036f"

      def install
        bin.install "lockenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/illarion/lockenv/releases/download/v0.1.1/lockenv_0.1.1_darwin_arm64.tar.gz"
      sha256 "006421fb258ae9b055d5218b95bf800d1b8e69777f513c3f50414c092d3927a0"

      def install
        bin.install "lockenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/illarion/lockenv/releases/download/v0.1.1/lockenv_0.1.1_linux_amd64.tar.gz"
      sha256 "a0bd43cafa9dd7622e117c8ae6b2ce5b1a80844741fcf1c4c2062b4ade232aee"
      def install
        bin.install "lockenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/illarion/lockenv/releases/download/v0.1.1/lockenv_0.1.1_linux_arm64.tar.gz"
      sha256 "a05c976f491b93a700d1ac7e21973344e0ff058e8c69f420c303e2707043d0e8"
      def install
        bin.install "lockenv"
      end
    end
  end
end
