# This file was generated by GoReleaser. DO NOT EDIT.
cask "lockenv" do
  name "lockenv"
  desc "Simple, CLI-friendly secret storage"
  homepage "https://github.com/illarion/lockenv"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lockenv"
  bash_completion "./completions/lockenv.bash"
  zsh_completion "./completions/_lockenv"
  fish_completion "./completions/lockenv.fish"

  on_macos do
    on_intel do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_darwin_amd64.tar.gz"
      sha256 "b80628be2037e781b49962caf000e2724ac96a081cde4e791edc5fdaacf87594"
    end
    on_arm do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_darwin_arm64.tar.gz"
      sha256 "e3b848745631fd6738c36287c422ccb6790b8824f8390caff81113c090aa7d3c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_linux_amd64.tar.gz"
      sha256 "da05295122e767d4ea29a02fb1a91b0e7582e4fd7a1d407a827bde9cfe5560d4"
    end
    on_arm do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_linux_arm64.tar.gz"
      sha256 "84c64794afb3568cba70818df8bb48dc214e2e644d1cf5c959fecb6b6c102510"
    end
  end

  # No zap stanza required
end
