# This file was generated by GoReleaser. DO NOT EDIT.
cask "lockenv" do
  name "lockenv"
  desc "Simple, CLI-friendly secret storage"
  homepage "https://github.com/illarion/lockenv"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lockenv"

  on_macos do
    on_intel do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_darwin_amd64.tar.gz"
      sha256 "ba35d567f59aa71326c4e6b895ac28544015644b0c2c09ebca7313eb20b6678b"
    end
    on_arm do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_darwin_arm64.tar.gz"
      sha256 "9d1aced9a08c34b77e335426f1e4665577f9de738810a3913d98d952f690aa21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_linux_amd64.tar.gz"
      sha256 "7f9c91f4931f31c91fbaf1e335c02a5dec0ffc37892d55274bfe30f926a90ff5"
    end
    on_arm do
      url "https://github.com/illarion/lockenv/releases/download/v#{version}/lockenv_#{version}_linux_arm64.tar.gz"
      sha256 "66438af4567fad4e8174b700254a0afb0fbc9f4223c1adf5366596b4ad2c0a83"
    end
  end

  # No zap stanza required
end
